import type { Json } from "@/types/database";

export type BuiltInTemplate = {
  category: "비즈니스" | "포트폴리오" | "쇼핑몰" | "기타";
  description: string;
  id: string;
  isFeatured: boolean;
  name: string;
  status: "active" | "featured";
  templateJson: Json;
  thumbnailUrl: string;
};

type TemplateSeed = {
  accent: string;
  audience: string;
  background: string;
  badge: string;
  category: BuiltInTemplate["category"];
  cta: string;
  description: string;
  featureItems: string[];
  featured?: boolean;
  footer: string;
  heroLayout: string;
  heroTitle: string;
  id: string;
  name: string;
  proofItems: string[];
  proofTitle: string;
  proofType: "review" | "stats";
  secondary: string;
};

function createTemplateJson(seed: TemplateSeed) {
  const proofSection =
    seed.proofType === "stats"
      ? {
          backgroundType: "color",
          badge: "Numbers",
          bgColor: seed.footer,
          description: "핵심 경쟁력을 숫자로 명확하게 전달합니다.",
          items: seed.proofItems,
          layout: "dark",
          paddingBottom: "88",
          paddingTop: "88",
          textColor: "#ffffff",
          title: seed.proofTitle,
          titleColor: "#ffffff",
          type: "stats",
          width: "1200",
        }
      : {
          backgroundType: "color",
          badge: "Reviews",
          bgColor: seed.background,
          description: "실제 고객의 경험으로 서비스의 신뢰를 높입니다.",
          items: seed.proofItems,
          layout: "rating",
          paddingBottom: "88",
          paddingTop: "88",
          title: seed.proofTitle,
          type: "review",
          width: "1200",
        };

  return {
    design: {
      bodyFontFamily: "pretendard",
      englishFontFamily: "pretendard",
      footerAccentColor: seed.accent,
      footerBgColor: seed.footer,
      footerLayout: "info",
      footerTextColor: "#f8fafc",
      headerBgColor: "#ffffff",
      headerButtonBgColor: seed.accent,
      headerButtonTextColor: "#ffffff",
      headerLayout: "center",
      headerPosition: "fixed",
      headerTextColor: "#111827",
      headingFontFamily: "pretendard",
      innerWidth: "1200",
      mainColor: seed.accent,
      sectionGap: "80",
      subColor: seed.secondary,
      textColor: "#111827",
    },
    sections: [
      {
        backgroundType: "gradient",
        badge: seed.badge,
        buttonLabel: "상담 문의하기",
        buttonLink: "/contact",
        description: seed.description,
        gradientFrom: seed.background,
        gradientTo: "#ffffff",
        layout: seed.heroLayout,
        mediaPosition: "right",
        paddingBottom: "112",
        paddingTop: "112",
        secondaryButtonLabel: "서비스 보기",
        secondaryButtonLink: "/service",
        title: seed.heroTitle,
        type: "hero",
        width: "1200",
      },
      {
        backgroundType: "color",
        badge: "Our Service",
        bgColor: "#ffffff",
        description: seed.audience,
        items: seed.featureItems,
        layout: "cards",
        paddingBottom: "96",
        paddingTop: "96",
        title: "고객이 필요한 정보를 한눈에",
        type: "features",
        width: "1200",
      },
      {
        backgroundType: "color",
        badge: "About",
        bgColor: seed.background,
        bodyText:
          "브랜드의 전문성과 차별점을 안정적인 모듈형 레이아웃에 담았습니다. 실제 사진과 핵심 문구만 교체하면 바로 사용할 수 있습니다.",
        description: "업종에 맞춘 정보 구조로 방문자의 이해와 행동을 자연스럽게 연결합니다.",
        layout: "media-left",
        mediaPosition: "left",
        paddingBottom: "96",
        paddingTop: "96",
        title: `${seed.name}에 맞춘 신뢰도 높은 구성`,
        type: "content",
        width: "1200",
      },
      proofSection,
      {
        backgroundType: "gradient",
        buttonLabel: "지금 문의하기",
        buttonLink: "/contact",
        buttonRadius: "8",
        description: "상담부터 서비스 이용까지 필요한 내용을 빠르게 안내해드립니다.",
        gradientFrom: seed.footer,
        gradientTo: seed.accent,
        layout: "banner",
        paddingBottom: "88",
        paddingTop: "88",
        textAlign: "center",
        title: seed.cta,
        titleColor: "#ffffff",
        descriptionColor: "#e2e8f0",
        type: "cta",
        width: "1200",
      },
    ],
    version: 1,
  } satisfies Json;
}

const templateSeeds: TemplateSeed[] = [
  {
    accent: "#2563eb",
    audience: "진료 분야, 의료진, 진료 시간과 예약 동선을 명확하게 구성했습니다.",
    background: "#eff6ff",
    badge: "Medical Clinic",
    category: "비즈니스",
    cta: "편안한 상담, 정확한 진료에서 시작됩니다",
    description: "신뢰할 수 있는 의료진과 체계적인 진료 과정을 한눈에 안내합니다.",
    featureItems: ["진료 과목 안내", "의료진 소개", "간편 예약 상담"],
    featured: true,
    footer: "#0f172a",
    heroLayout: "split-visual",
    heroTitle: "환자의 일상까지 생각하는 전문 의료 서비스",
    id: "builtin-medical-clinic",
    name: "병원·의료 클리닉",
    proofItems: ["누적 상담|1200|+", "진료 만족도|98|%", "전문 의료진|12|명"],
    proofTitle: "숫자로 확인하는 진료 신뢰도",
    proofType: "stats",
    secondary: "#dbeafe",
  },
  {
    accent: "#7c3aed",
    audience: "교육 과정, 강사진, 수강 후기와 상담 신청을 자연스럽게 연결합니다.",
    background: "#f5f3ff",
    badge: "Education Academy",
    category: "비즈니스",
    cta: "성장의 다음 단계를 함께 설계하세요",
    description: "학습 목표부터 성과까지, 선택에 필요한 교육 정보를 분명하게 보여줍니다.",
    featureItems: ["맞춤 교육 과정", "전문 강사진", "수강 상담"],
    footer: "#1e1b4b",
    heroLayout: "centered-showcase",
    heroTitle: "배움이 결과로 이어지는 교육을 만듭니다",
    id: "builtin-education-academy",
    name: "학원·교육 아카데미",
    proofItems: ["김하늘|수강생|체계적인 커리큘럼 덕분에 목표를 빠르게 달성했어요.", "박도윤|학부모|상담과 피드백이 꼼꼼해서 믿고 맡길 수 있었습니다."],
    proofTitle: "먼저 경험한 수강생의 이야기",
    proofType: "review",
    secondary: "#ede9fe",
  },
  {
    accent: "#0f766e",
    audience: "전문 분야, 업무 절차, 성공 사례와 상담 접점을 신뢰감 있게 배치했습니다.",
    background: "#f0fdfa",
    badge: "Professional Office",
    category: "비즈니스",
    cta: "복잡한 문제일수록 전문가와 먼저 상의하세요",
    description: "법률·세무·노무 등 전문 서비스의 경험과 해결 방식을 차분하게 전달합니다.",
    featureItems: ["전문 상담", "업무 분야", "사례 중심 안내"],
    featured: true,
    footer: "#042f2e",
    heroLayout: "text-focus",
    heroTitle: "의뢰인의 문제를 정확하게 이해하는 전문가",
    id: "builtin-professional-office",
    name: "법무·세무 전문사무소",
    proofItems: ["상담 경험|15|년", "누적 의뢰|2400|+", "재의뢰율|91|%"],
    proofTitle: "경험으로 증명하는 전문성",
    proofType: "stats",
    secondary: "#ccfbf1",
  },
  {
    accent: "#b45309",
    audience: "대표 메뉴, 공간 분위기, 운영 시간과 예약 정보를 감각적으로 보여줍니다.",
    background: "#fffbeb",
    badge: "Dining & Cafe",
    category: "기타",
    cta: "오늘의 좋은 시간을 미리 예약하세요",
    description: "메뉴와 공간의 매력이 방문으로 이어지도록 첫 화면부터 풍성하게 구성했습니다.",
    featureItems: ["시그니처 메뉴", "공간 소개", "예약·오시는 길"],
    footer: "#292524",
    heroLayout: "template-showcase",
    heroTitle: "한 접시와 한 공간에 담은 우리의 취향",
    id: "builtin-dining-cafe",
    name: "레스토랑·카페",
    proofItems: ["이서연|방문 고객|음식뿐 아니라 공간과 서비스까지 오래 기억에 남아요.", "정우진|단골 고객|계절마다 새로운 메뉴를 기대하게 되는 곳입니다."],
    proofTitle: "공간을 기억하는 고객 후기",
    proofType: "review",
    secondary: "#fef3c7",
  },
  {
    accent: "#db2777",
    audience: "시술 메뉴, 스타일 포트폴리오, 디자이너와 예약 정보를 빠르게 탐색할 수 있습니다.",
    background: "#fdf2f8",
    badge: "Beauty Studio",
    category: "포트폴리오",
    cta: "당신다운 스타일을 지금 예약하세요",
    description: "결과 이미지와 섬세한 서비스 경험이 돋보이는 뷰티 전용 구성입니다.",
    featureItems: ["시술 프로그램", "스타일 갤러리", "디자이너 예약"],
    footer: "#3f1027",
    heroLayout: "editorial-contrast",
    heroTitle: "가장 나다운 아름다움을 디자인합니다",
    id: "builtin-beauty-studio",
    name: "뷰티·헤어 스튜디오",
    proofItems: ["윤지아|헤어 고객|원하는 분위기를 정확히 이해하고 더 멋지게 제안해주셨어요.", "최민서|뷰티 고객|예약부터 관리 안내까지 섬세해서 만족했습니다."],
    proofTitle: "변화를 경험한 고객 이야기",
    proofType: "review",
    secondary: "#fce7f3",
  },
  {
    accent: "#475569",
    audience: "프로젝트 포트폴리오, 설계 철학, 진행 과정과 상담 정보를 구조적으로 담았습니다.",
    background: "#f8fafc",
    badge: "Architecture Studio",
    category: "포트폴리오",
    cta: "당신의 공간에 필요한 이야기를 들려주세요",
    description: "완성된 공간과 설계 과정을 큰 이미지와 절제된 타이포로 전달합니다.",
    featureItems: ["프로젝트 사례", "설계 프로세스", "공간 상담"],
    footer: "#111827",
    heroLayout: "product-canvas",
    heroTitle: "삶의 방식에서 시작하는 공간 디자인",
    id: "builtin-architecture-studio",
    name: "인테리어·건축 스튜디오",
    proofItems: ["완료 프로젝트|86|건", "평균 경력|11|년", "고객 추천|96|%"],
    proofTitle: "완성도 높은 공간을 만드는 기준",
    proofType: "stats",
    secondary: "#e2e8f0",
  },
  {
    accent: "#2563eb",
    audience: "제품 가치, 주요 기능, 도입 효과와 데모 신청을 SaaS 흐름에 맞게 구성했습니다.",
    background: "#eef4ff",
    badge: "B2B SaaS",
    category: "비즈니스",
    cta: "팀의 다음 성장을 지금 시작하세요",
    description: "복잡한 업무를 단순하게 바꾸는 제품의 가치를 실제 화면 중심으로 설명합니다.",
    featureItems: ["업무 자동화", "실시간 협업", "데이터 인사이트"],
    featured: true,
    footer: "#0b1220",
    heroLayout: "product-canvas",
    heroTitle: "더 적은 반복으로 더 큰 성과를 만드는 SaaS",
    id: "builtin-saas-startup",
    name: "스타트업·SaaS",
    proofItems: ["업무 시간 절감|42|%", "활성 사용자|18|K", "서비스 가동률|99.9|%"],
    proofTitle: "팀의 성과로 확인된 변화",
    proofType: "stats",
    secondary: "#dbeafe",
  },
  {
    accent: "#059669",
    audience: "브랜드 스토리, 대표 상품, 구매 혜택과 후기까지 쇼핑 흐름에 맞게 배치했습니다.",
    background: "#ecfdf5",
    badge: "Brand Shop",
    category: "쇼핑몰",
    cta: "매일 쓰고 싶은 브랜드를 만나보세요",
    description: "상품의 디테일과 브랜드 철학이 함께 보이는 감도 높은 커머스 구성입니다.",
    featureItems: ["베스트 상품", "브랜드 스토리", "구매·배송 안내"],
    featured: true,
    footer: "#052e2b",
    heroLayout: "template-showcase",
    heroTitle: "좋은 취향이 오래 머무는 라이프스타일 브랜드",
    id: "builtin-brand-shop",
    name: "브랜드·쇼핑몰",
    proofItems: ["한유진|구매 고객|제품의 완성도와 포장이 모두 브랜드답고 섬세해요.", "서지훈|재구매 고객|매일 사용해도 질리지 않는 디자인이 마음에 듭니다."],
    proofTitle: "브랜드를 선택한 고객의 목소리",
    proofType: "review",
    secondary: "#d1fae5",
  },
  {
    accent: "#ea580c",
    audience: "대표 작업, 전문 분야, 작업 과정과 협업 문의를 포트폴리오 중심으로 구성했습니다.",
    background: "#fff7ed",
    badge: "Creative Portfolio",
    category: "포트폴리오",
    cta: "새로운 프로젝트를 함께 시작해볼까요?",
    description: "작업 결과가 가장 먼저 보이고, 창작자의 관점과 역량이 자연스럽게 이어집니다.",
    featureItems: ["대표 프로젝트", "작업 분야", "협업 문의"],
    footer: "#431407",
    heroLayout: "editorial-contrast",
    heroTitle: "아이디어를 선명한 결과물로 만드는 크리에이터",
    id: "builtin-creator-portfolio",
    name: "크리에이터 포트폴리오",
    proofItems: ["브랜드 작업|64|건", "협업 파트너|38|팀", "프로젝트 만족도|97|%"],
    proofTitle: "작업과 협업으로 쌓은 기록",
    proofType: "stats",
    secondary: "#ffedd5",
  },
  {
    accent: "#0284c7",
    audience: "객실·공간, 주변 경험, 이용 안내와 예약 동선을 여행자의 시선에 맞췄습니다.",
    background: "#f0f9ff",
    badge: "Stay & Place",
    category: "기타",
    cta: "머물고 싶은 날짜를 지금 확인하세요",
    description: "공간의 분위기와 머무는 경험을 넓은 비주얼과 편안한 정보 구조로 전합니다.",
    featureItems: ["객실과 공간", "주변의 경험", "예약·이용 안내"],
    footer: "#0c4a6e",
    heroLayout: "split-visual",
    heroTitle: "일상에서 잠시 멀어지는 가장 편안한 공간",
    id: "builtin-stay-place",
    name: "숙박·스테이",
    proofItems: ["김다은|투숙객|사진에서 느낀 분위기보다 실제 공간이 더 좋았습니다.", "오현우|투숙객|안내가 세심하고 주변을 즐기기에도 좋은 위치였어요."],
    proofTitle: "이곳에 머문 사람들의 이야기",
    proofType: "review",
    secondary: "#e0f2fe",
  },
];

export const builtInTemplates: BuiltInTemplate[] = templateSeeds.map((seed) => ({
  category: seed.category,
  description: seed.description,
  id: seed.id,
  isFeatured: seed.featured ?? false,
  name: seed.name,
  status: seed.featured ? "featured" : "active",
  templateJson: createTemplateJson(seed),
  thumbnailUrl: "",
}));

export function getBuiltInTemplate(templateId: string) {
  return builtInTemplates.find((template) => template.id === templateId) ?? null;
}
